### ISSUE TITLE
Recent searches improvement

### ISSUE THREAD

**Issue by abadoliverco** [Drabu/PlaceAutocomplete#6]
Hi, I like your library it's easy to use and very straight forward but I noticed that you're calling the details API again when you click the item on the recent searches, why do you need to do that? you already saved the details in your local DB, we can save the daily usage of the API if we don't need to query again. Thank you! just a thought. :)

**Comment by Drabu** [comment]
Thanks @abadoliverco Glad you liked  it, The only problem with that is when there is an update on any of its details, the local db would be sharing outdated data so to avoid the same i've made another api call just be sure that the data is up to date, but sure, can have a different flavor of the same;
